package com.dao;

import com.model.jibenxinxi;

public interface jibenxinxiMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jibenxinxi
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jibenxinxi
     *
     * @mbggenerated
     */
    int insert(jibenxinxi record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jibenxinxi
     *
     * @mbggenerated
     */
    int insertSelective(jibenxinxi record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jibenxinxi
     *
     * @mbggenerated
     */
    jibenxinxi selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jibenxinxi
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(jibenxinxi record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jibenxinxi
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(jibenxinxi record);
}