package com.dao;

import com.model.lianzubutie;

public interface lianzubutieMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lianzubutie
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lianzubutie
     *
     * @mbggenerated
     */
    int insert(lianzubutie record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lianzubutie
     *
     * @mbggenerated
     */
    int insertSelective(lianzubutie record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lianzubutie
     *
     * @mbggenerated
     */
    lianzubutie selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lianzubutie
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(lianzubutie record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lianzubutie
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(lianzubutie record);
}