package com.dao;

import com.model.minzu;

public interface minzuMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table minzu
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String minzuCode);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table minzu
     *
     * @mbggenerated
     */
    int insert(minzu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table minzu
     *
     * @mbggenerated
     */
    int insertSelective(minzu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table minzu
     *
     * @mbggenerated
     */
    minzu selectByPrimaryKey(String minzuCode);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table minzu
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(minzu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table minzu
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(minzu record);
}