package com.dao;

import java.util.List;

import com.model.xingzhengquyu;

public interface xingzhengquyuMapper {
	

    List<xingzhengquyu> selectAll();
    
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xingzhengquyu
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String xingzhengquyuCode);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xingzhengquyu
     *
     * @mbggenerated
     */
    int insert(xingzhengquyu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xingzhengquyu
     *
     * @mbggenerated
     */
    int insertSelective(xingzhengquyu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xingzhengquyu
     *
     * @mbggenerated
     */
    xingzhengquyu selectByPrimaryKey(String xingzhengquyuCode);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xingzhengquyu
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(xingzhengquyu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xingzhengquyu
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(xingzhengquyu record);
}