package com.dao;

import com.model.yinhangleibie;

public interface yinhangleibieMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yinhangleibie
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String leibieCode);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yinhangleibie
     *
     * @mbggenerated
     */
    int insert(yinhangleibie record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yinhangleibie
     *
     * @mbggenerated
     */
    int insertSelective(yinhangleibie record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yinhangleibie
     *
     * @mbggenerated
     */
    yinhangleibie selectByPrimaryKey(String leibieCode);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yinhangleibie
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(yinhangleibie record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yinhangleibie
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(yinhangleibie record);
}