package com.model;

import java.io.Serializable;

public class jibenxinxi implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jibenxinxi.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jibenxinxi.xingming
     *
     * @mbggenerated
     */
    private String xingming;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jibenxinxi.shenfenzheng
     *
     * @mbggenerated
     */
    private String shenfenzheng;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jibenxinxi.phone
     *
     * @mbggenerated
     */
    private String phone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jibenxinxi.xingzhengquyu_code
     *
     * @mbggenerated
     */
    private String xingzhengquyuCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jibenxinxi.minzu_code
     *
     * @mbggenerated
     */
    private String minzuCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jibenxinxi.jibenxinxicol
     *
     * @mbggenerated
     */
    private String jibenxinxicol;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jibenxinxi.address
     *
     * @mbggenerated
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table jibenxinxi
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jibenxinxi.id
     *
     * @return the value of jibenxinxi.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jibenxinxi.id
     *
     * @param id the value for jibenxinxi.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jibenxinxi.xingming
     *
     * @return the value of jibenxinxi.xingming
     *
     * @mbggenerated
     */
    public String getXingming() {
        return xingming;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jibenxinxi.xingming
     *
     * @param xingming the value for jibenxinxi.xingming
     *
     * @mbggenerated
     */
    public void setXingming(String xingming) {
        this.xingming = xingming == null ? null : xingming.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jibenxinxi.shenfenzheng
     *
     * @return the value of jibenxinxi.shenfenzheng
     *
     * @mbggenerated
     */
    public String getShenfenzheng() {
        return shenfenzheng;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jibenxinxi.shenfenzheng
     *
     * @param shenfenzheng the value for jibenxinxi.shenfenzheng
     *
     * @mbggenerated
     */
    public void setShenfenzheng(String shenfenzheng) {
        this.shenfenzheng = shenfenzheng == null ? null : shenfenzheng.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jibenxinxi.phone
     *
     * @return the value of jibenxinxi.phone
     *
     * @mbggenerated
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jibenxinxi.phone
     *
     * @param phone the value for jibenxinxi.phone
     *
     * @mbggenerated
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jibenxinxi.xingzhengquyu_code
     *
     * @return the value of jibenxinxi.xingzhengquyu_code
     *
     * @mbggenerated
     */
    public String getXingzhengquyuCode() {
        return xingzhengquyuCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jibenxinxi.xingzhengquyu_code
     *
     * @param xingzhengquyuCode the value for jibenxinxi.xingzhengquyu_code
     *
     * @mbggenerated
     */
    public void setXingzhengquyuCode(String xingzhengquyuCode) {
        this.xingzhengquyuCode = xingzhengquyuCode == null ? null : xingzhengquyuCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jibenxinxi.minzu_code
     *
     * @return the value of jibenxinxi.minzu_code
     *
     * @mbggenerated
     */
    public String getMinzuCode() {
        return minzuCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jibenxinxi.minzu_code
     *
     * @param minzuCode the value for jibenxinxi.minzu_code
     *
     * @mbggenerated
     */
    public void setMinzuCode(String minzuCode) {
        this.minzuCode = minzuCode == null ? null : minzuCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jibenxinxi.jibenxinxicol
     *
     * @return the value of jibenxinxi.jibenxinxicol
     *
     * @mbggenerated
     */
    public String getJibenxinxicol() {
        return jibenxinxicol;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jibenxinxi.jibenxinxicol
     *
     * @param jibenxinxicol the value for jibenxinxi.jibenxinxicol
     *
     * @mbggenerated
     */
    public void setJibenxinxicol(String jibenxinxicol) {
        this.jibenxinxicol = jibenxinxicol == null ? null : jibenxinxicol.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jibenxinxi.address
     *
     * @return the value of jibenxinxi.address
     *
     * @mbggenerated
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jibenxinxi.address
     *
     * @param address the value for jibenxinxi.address
     *
     * @mbggenerated
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }
}