package com.model;

import java.io.Serializable;

public class lianzubutie implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lianzubutie.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lianzubutie.jibenxinxi_id
     *
     * @mbggenerated
     */
    private Integer jibenxinxiId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lianzubutie.dibaozheng
     *
     * @mbggenerated
     */
    private String dibaozheng;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lianzubutie.butiejine
     *
     * @mbggenerated
     */
    private String butiejine;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lianzubutie.yinhangleibie_code
     *
     * @mbggenerated
     */
    private String yinhangleibieCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lianzubutie.kaihuming
     *
     * @mbggenerated
     */
    private String kaihuming;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lianzubutie.yinhangzhanghao
     *
     * @mbggenerated
     */
    private String yinhangzhanghao;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table lianzubutie
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lianzubutie.id
     *
     * @return the value of lianzubutie.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lianzubutie.id
     *
     * @param id the value for lianzubutie.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lianzubutie.jibenxinxi_id
     *
     * @return the value of lianzubutie.jibenxinxi_id
     *
     * @mbggenerated
     */
    public Integer getJibenxinxiId() {
        return jibenxinxiId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lianzubutie.jibenxinxi_id
     *
     * @param jibenxinxiId the value for lianzubutie.jibenxinxi_id
     *
     * @mbggenerated
     */
    public void setJibenxinxiId(Integer jibenxinxiId) {
        this.jibenxinxiId = jibenxinxiId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lianzubutie.dibaozheng
     *
     * @return the value of lianzubutie.dibaozheng
     *
     * @mbggenerated
     */
    public String getDibaozheng() {
        return dibaozheng;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lianzubutie.dibaozheng
     *
     * @param dibaozheng the value for lianzubutie.dibaozheng
     *
     * @mbggenerated
     */
    public void setDibaozheng(String dibaozheng) {
        this.dibaozheng = dibaozheng == null ? null : dibaozheng.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lianzubutie.butiejine
     *
     * @return the value of lianzubutie.butiejine
     *
     * @mbggenerated
     */
    public String getButiejine() {
        return butiejine;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lianzubutie.butiejine
     *
     * @param butiejine the value for lianzubutie.butiejine
     *
     * @mbggenerated
     */
    public void setButiejine(String butiejine) {
        this.butiejine = butiejine == null ? null : butiejine.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lianzubutie.yinhangleibie_code
     *
     * @return the value of lianzubutie.yinhangleibie_code
     *
     * @mbggenerated
     */
    public String getYinhangleibieCode() {
        return yinhangleibieCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lianzubutie.yinhangleibie_code
     *
     * @param yinhangleibieCode the value for lianzubutie.yinhangleibie_code
     *
     * @mbggenerated
     */
    public void setYinhangleibieCode(String yinhangleibieCode) {
        this.yinhangleibieCode = yinhangleibieCode == null ? null : yinhangleibieCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lianzubutie.kaihuming
     *
     * @return the value of lianzubutie.kaihuming
     *
     * @mbggenerated
     */
    public String getKaihuming() {
        return kaihuming;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lianzubutie.kaihuming
     *
     * @param kaihuming the value for lianzubutie.kaihuming
     *
     * @mbggenerated
     */
    public void setKaihuming(String kaihuming) {
        this.kaihuming = kaihuming == null ? null : kaihuming.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lianzubutie.yinhangzhanghao
     *
     * @return the value of lianzubutie.yinhangzhanghao
     *
     * @mbggenerated
     */
    public String getYinhangzhanghao() {
        return yinhangzhanghao;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lianzubutie.yinhangzhanghao
     *
     * @param yinhangzhanghao the value for lianzubutie.yinhangzhanghao
     *
     * @mbggenerated
     */
    public void setYinhangzhanghao(String yinhangzhanghao) {
        this.yinhangzhanghao = yinhangzhanghao == null ? null : yinhangzhanghao.trim();
    }
}