package com.model;

import java.io.Serializable;

public class xingzhengquyu implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xingzhengquyu.xingzhengquyu_code
     *
     * @mbggenerated
     */
    private String xingzhengquyuCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xingzhengquyu.xingzhengquyu_name
     *
     * @mbggenerated
     */
    private String xingzhengquyuName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table xingzhengquyu
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xingzhengquyu.xingzhengquyu_code
     *
     * @return the value of xingzhengquyu.xingzhengquyu_code
     *
     * @mbggenerated
     */
    public String getXingzhengquyuCode() {
        return xingzhengquyuCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xingzhengquyu.xingzhengquyu_code
     *
     * @param xingzhengquyuCode the value for xingzhengquyu.xingzhengquyu_code
     *
     * @mbggenerated
     */
    public void setXingzhengquyuCode(String xingzhengquyuCode) {
        this.xingzhengquyuCode = xingzhengquyuCode == null ? null : xingzhengquyuCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xingzhengquyu.xingzhengquyu_name
     *
     * @return the value of xingzhengquyu.xingzhengquyu_name
     *
     * @mbggenerated
     */
    public String getXingzhengquyuName() {
        return xingzhengquyuName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xingzhengquyu.xingzhengquyu_name
     *
     * @param xingzhengquyuName the value for xingzhengquyu.xingzhengquyu_name
     *
     * @mbggenerated
     */
    public void setXingzhengquyuName(String xingzhengquyuName) {
        this.xingzhengquyuName = xingzhengquyuName == null ? null : xingzhengquyuName.trim();
    }
}