package com.model;

import java.io.Serializable;

public class yinhangleibie implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yinhangleibie.leibie_code
     *
     * @mbggenerated
     */
    private String leibieCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yinhangleibie.leibie_name
     *
     * @mbggenerated
     */
    private String leibieName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table yinhangleibie
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yinhangleibie.leibie_code
     *
     * @return the value of yinhangleibie.leibie_code
     *
     * @mbggenerated
     */
    public String getLeibieCode() {
        return leibieCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yinhangleibie.leibie_code
     *
     * @param leibieCode the value for yinhangleibie.leibie_code
     *
     * @mbggenerated
     */
    public void setLeibieCode(String leibieCode) {
        this.leibieCode = leibieCode == null ? null : leibieCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yinhangleibie.leibie_name
     *
     * @return the value of yinhangleibie.leibie_name
     *
     * @mbggenerated
     */
    public String getLeibieName() {
        return leibieName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yinhangleibie.leibie_name
     *
     * @param leibieName the value for yinhangleibie.leibie_name
     *
     * @mbggenerated
     */
    public void setLeibieName(String leibieName) {
        this.leibieName = leibieName == null ? null : leibieName.trim();
    }
}